### PR TITLE
Make kpi forecasting pip installable

### PR DESCRIPTION
**Pull request by bochocki**
This PR performs makes a few mostly cosmetic changes so that `kpi-forecasting` can be installed with pip for use in Jupyter/Colab notebooks.

This branch can be pip-installed with the following command:
```
pip install -e 'git+https://github.com/mozilla/docker-etl@make_kpi-forecasting_pip_installable#egg=kpi_forecasting&subdirectory=jobs/kpi-forecasting/' \
  -r "https://raw.githubusercontent.com/mozilla/docker-etl/main/jobs/kpi-forecasting/requirements.txt"
```

An [example notebook is here](https://colab.research.google.com/drive/1HaqgSyAmKiu5PkCsvoRd4IOuLJWZJfr_#scrollTo=lNMZwwnNZdJA).

There is another PR for the corresponding Airflow job that needs to be merged at the same time: https://github.com/mozilla/telemetry-airflow/pull/1833

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is
  referenced, the pull request should include the bug number in the title)
- [ ] Scan the PR and verify that no changes (particularly to
  `.circleci/config.yml`) will cause environment variables (particularly
  credentials) to be exposed in test logs
- [ ] Ensure the container image will be using permissions granted to
  [telemetry-airflow](https://github.com/mozilla/telemetry-airflow/)
  responsibly.

### CODE REVIEW

**Review by gkabbz — APPROVED** [review]

**Comment by akkomar** [comment]
@bochocki kpi_forecasting task started failing on Friday with the following error:
```
[2023-10-14, 06:04:32 UTC] {pod_manager.py:235} INFO - ImportError: cannot import name 'ProphetForecast' from partially initialized module 'models.prophet_forecast' (most likely due to a circular import) (/app/kpi_forecasting/models/prophet_forecast.py)
```
Might be related to this change.

**Comment by bochocki** [comment]
@akkomar Thanks for catching this. There was an issue in the module setup that I didn't catch when testing locally. The task is succeeding now after merging these PRs:
- https://github.com/mozilla/docker-etl/pull/158
- https://github.com/mozilla/telemetry-airflow/pull/1835
